version: "3.3"

networks:
   main:
      driver: bridge
   sources:
      driver: bridge

volumes:
   stream_config:
      driver: local

services:
   backend:
      image: radiobretzel/backend:dev
      build:
         context: ./backend/
         dockerfile: dockerfiles/dev
      depends_on:
         - database
      ports:
         - 80:5000
      volumes:
         - ./backend/:/usr/src/radiobretzel
         - /var/run/docker.sock:/var/run/docker.sock
         # - stream_config:/usr/src/stream_config
      networks:
         main:
            aliases:
               - backend.main.radiobretzel
         sources:
            aliases:
               - backend.sources.radiobretzel
   database:
      image: mongo
      networks:
         main:
            aliases:
               - database.main.radiobretzel
   streaming:
      image: radiobretzel/stream:dev
      build:
         context: ./stream/
         dockerfile: dockerfiles/dev
      ports:
         - 8000:8000
      volumes:
         - ./stream:/usr/src/stream_config
      networks:
         sources:
            aliases:
               - streaming.sources.radiobretzel
